import 'package:flutter_tts/flutter_tts.dart';
import 'package:get/get.dart';

import '../model/character_model.dart';

class CharacterWiseObjectController extends GetxController {
  final FlutterTts flutterTts = FlutterTts();
  final charactersList = <CharacterObjectModel>[
    CharacterObjectModel(character: 'A', objects: [
      {'name': 'Apple', 'image': 'https://static.wikia.nocookie.net/the-snack-encyclopedia/images/7/7d/Apple.png/revision/latest?cb=20200706145821'},
      {'name': 'Ant', 'image': 'https://www.adamspetcare.com/-/media/Project/OneWeb/Adams/Images/Photos/Blog/Article/ants.jpg'},
      {'name': 'Aeroplane', 'image': 'https://t4.ftcdn.net/jpg/08/71/56/43/360_F_871564379_dYGGRSxybQq1Z2FHh6iwySw1Xp7AiDNF.jpg'},
      {'name': 'Alligator', 'image': 'https://www.shutterstock.com/image-vector/virtual-reality-alligator-vector-paleontology-600nw-2303842673.jpg'},
      {'name': 'Arrow', 'image': 'https://www.shutterstock.com/image-vector/red-arrow-icon-on-white-600nw-2484198151.jpg'},
      {'name': 'Axe', 'image': 'https://assets.katogroup.eu/i/katogroup/MR703_01_marbles'},
      {'name': 'Apron', 'image': 'https://www.ikea.com/us/en/images/products/sandviva-apron-dark-gray__1329413_pe945160_s5.jpg?f=s'},
      {'name': 'Almond', 'image': 'https://media.istockphoto.com/id/1453155067/photo/close-up-of-delicious-single-almond-on-white.jpg?s=612x612&w=0&k=20&c=OYVbNZUZ-rHaSnUTtTVTyetV0LiOHM2DcqMR_sSlBvw='},
      {'name': 'Anchor', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrTEs-XL6gGc9-aM05d5HTEyRk6dI7iehnnw&s'},
      {'name': 'Avocado', 'image': 'https://cdn.britannica.com/72/170772-050-D52BF8C2/Avocado-fruits.jpg'},
    ]),

    CharacterObjectModel(character: 'B', objects: [
      {'name': 'Ball', 'image': 'https://dmzn2b8hkpq8b.cloudfront.net/images/products/515x515/S284990.jpg'},
      {'name': 'Banana', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ65Yp_7e4roHU7AnEDjkRriZb26JE5jEH9Bw&s'},
      {'name': 'Bat', 'image': 'https://media.umbraco.io/serious-sports-group/gm5ac4ew/12.png?height=0&width=977&quality=100&mode=crop&center=0.5,0.5'},
      {'name': 'Bird', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvdE_IHgM5Feei-LstUWxQVTIc9FgOTG1B1A&s'},
      {'name': 'Butterfly', 'image': 'https://thumbs.dreamstime.com/b/flying-butterfly-orange-shadow-isolated-white-background-illustration-38959015.jpg'},
      {'name': 'Book', 'image': 'https://media.istockphoto.com/id/173015527/photo/a-single-red-book-on-a-white-surface.jpg?s=612x612&w=0&k=20&c=AeKmdZvg2_bRY2Yct7odWhZXav8CgDtLMc_5_pjSItY='},
      {'name': 'Bus', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX20PBCZKxq17ZClmrvT7F9540Qp6DQsAWg7nC5YQwi80Hl9TGD5wtAc7qgY0rP6BQHjk&usqp=CAU'},
      {'name': 'Bell', 'image': 'https://www.shutterstock.com/image-vector/gold-vintage-retro-school-bell-600nw-2556965341.jpg'},
      {'name': 'Boat', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpiNOJBUsS_MgReZB9XnvNdD3lQAtlmKlH5w&s'},
      {'name': 'Balloon', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLvOmpHdV-Pm9F32Kw6_9fTAaNMPUAYipRTA&s'},

    ]),
    CharacterObjectModel(character: 'C', objects: [
      {'name': 'Cat', 'image': 'https://media.istockphoto.com/id/1443562748/photo/cute-ginger-cat.jpg?s=612x612&w=0&k=20&c=vvM97wWz-hMj7DLzfpYRmY2VswTqcFEKkC437hxm3Cg='},
      {'name': 'Car', 'image': 'https://image.made-in-china.com/202f0j00EwtcpBFnkIkJ/New-Exeed-Strerra-Et-4WD-Pure-Electric-Car-EV-Avto.webp'},
      {'name': 'Cake', 'image': 'https://thumbs.dreamstime.com/b/happy-birthday-cake-isolated-transparent-background-happy-birthday-cake-isolated-transparent-white-background-288617154.jpg'},
      {'name': 'Cow', 'image': 'https://www.shutterstock.com/image-photo/black-white-dairy-cow-clear-600nw-2628118303.jpg'},
      {'name': 'Cap', 'image': 'https://customlids.ca/cdn/shop/products/21374192_02.jpg?v=1657065319'},
      {'name': 'Clock', 'image': 'https://cdn.pixabay.com/photo/2017/03/26/12/36/alarm-clock-2175382_1280.jpg'},
      {'name': 'Candle', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLfpbwEkZEpmRpgHnYNhisH6UmIyYgqFiq1MSavPro-jPDsO6O2lD07gblf0HRxYdtzsw&usqp=CAU'},
      {'name': 'Cloud', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-vM1xKOynb_jDQ4bw0G7-lkoop8_fUjipmaE0V6WbyW7FYSwQ7OnGq_7bxgh_rLxT91E&usqp=CAU'},
      {'name': 'Corn', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQGFKj29zKM7lIpMgAM4k4f513xlyUyS90cg&s'},
      {'name': 'Cup', 'image': 'https://www.forlifedesignusa.com/cdn/shop/products/550-TRQ.jpg?v=1581640656'},
    ]),
    CharacterObjectModel(character: 'D', objects: [
      {'name': 'Dog', 'image': 'https://thumbs.dreamstime.com/b/side-view-golden-retriever-panting-standing-front-isolated-white-376594274.jpg'},
      {'name': 'Doll', 'image': 'https://t3.ftcdn.net/jpg/00/62/18/54/360_F_62185421_cVM7RxbG5c2GAeJWMDtgyOiEM1iHyTOR.jpg'},
      {'name': 'Duck', 'image': 'https://s3.us-west-2.amazonaws.com/cdn.classful.com/wp-content/uploads/2023/08/64ebef38903ed16070706591693183800413-img-6393.jpeg'},
      {'name': 'Drum', 'image': 'https://www.shutterstock.com/image-vector/snare-drum-vector-isolated-illustration-600nw-2325704019.jpg'},
      {'name': 'Door', 'image': 'https://www.neuffer.de/sites/de/files/img/frontdoors/l/country-house-door-pine-wood.jpg'},
      {'name': 'Donkey', 'image': 'https://cdn.vectorstock.com/i/1000v/20/27/cartoon-donkey-animal-vector-44712027.jpg'},
      {'name': 'Diamond', 'image': 'https://docs.growndiamondcorp.com/blog/types-of-diamonds.png'},
      {'name': 'Desk', 'image': 'https://www.office-furniture-direct.co.uk/Cache/Images/MI003283-1-2048-2048-1500x1500-opaque.jpg'},
      {'name': 'Dolphin', 'image': 'https://sketchok.com/images/articles/07-animals/05-sea-animals/10/10.jpg'},
      {'name': 'Dress', 'image': 'https://img.bestdealplus.com/ae04/kf/S13dda55ab9e34deb87cf2eea49d4ff0bU.jpg'},
    ]),
    CharacterObjectModel(character: 'E', objects: [
      {'name': 'Egg', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'Elephant', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'Eagle', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'Earwig', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'Envelope', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Eggplant', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Ear', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
      {'name': 'Earth', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKF2MpLAHv1sM4hl5SuAASLrB7x4893b5fbg&s'},
      {'name': 'Engine', 'image': 'https://static.pakwheels.com/2016/09/corvette-engine.jpg'},
      {'name': 'Emu', 'image': 'https://easydrawingguides.com/wp-content/uploads/2024/05/how-to-draw-an-emu-featured-image-1200.png'},
    ]),
    CharacterObjectModel(character: 'F', objects: [
      {'name': 'Frog', 'image': 'https://www.bigappleherp.com/cdn/shop/products/800181L_groupgreentreefrog_1200x630.jpg?v=1548363542'},
      {'name': 'Fish', 'image': 'https://files.nc.gov/deq/styles/article_card/public/images/2021-10/atlantic-bonito.jpg?VersionId=9QEVa4aBWw5AhgQt6Y5lrmKitWoetlw5&itok=7yNIlyIm'},
      {'name': 'Fly', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkps3mkcpRa7KYdH9ZjWFChdP80SAo-yrs_dNue2uZELGi9ChEc9gm7q6VrOjgxXAnjIw&usqp=CAU'},
      {'name': 'Fox', 'image': 'https://st5.depositphotos.com/1497380/65020/v/450/depositphotos_650206534-stock-illustration-cartoon-fox-sitting.jpg'},
      {'name': 'Fries', 'image': 'https://pizzanfries.com.pk/wp-content/uploads/2023/10/Plain-French-Fries-pizza-n-fries.jpg'},
      {'name': 'Flower', 'image': 'https://media.istockphoto.com/id/510266545/photo/tulip.jpg?s=612x612&w=0&k=20&c=UcRWBONYuWcTpUd_DMo6w1rlmPgxh0Cb_oDWxmyyJK4='},
      {'name': 'Flamingo', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbzAltPLkVJDv_Dg2m2k-jVz1DKq7v-SdY1aHgzfc2frQoEok57g10EJMYflETAGk-gZM&usqp=CAU'},
      {'name': 'Fire', 'image': 'https://media.istockphoto.com/id/1323529010/vector/fire-vector-isolated.jpg?s=612x612&w=0&k=20&c=ta6bKkXZDuqy2H3tRhR79sSl_-fdGhKyoenbbjEr3l0='},
      {'name': 'Fire Truck', 'image': 'https://static.vecteezy.com/system/resources/previews/029/806/850/non_2x/red-fire-truck-illustration-emergency-rescue-truck-side-view-isolated-on-white-background-vector.jpg'},
      {'name': 'Feather', 'image': 'https://www.shutterstock.com/image-photo/beautiful-orange-bird-feather-isolated-600nw-2290953155.jpg'},
    ]),
    CharacterObjectModel(character: 'G', objects: [
      {'name': 'Goat', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_WfiisR30R7phfttyO0MfLdpI2eUNACCc2mgaRjm3abLfI2I0_wk5Zuian9ZVd3txzb0&usqp=CAU'},
      {'name': 'Gorilla', 'image': 'https://www.shutterstock.com/image-vector/gorilla-illustration-on-white-background-600nw-2433820107.jpg'},
      {'name': 'Giraffe', 'image': 'https://wallpapers.com/images/hd/giraffe-pictures-2aqk932hx81iw8n1.jpg'},
      {'name': 'Grapes', 'image': 'https://extension.psu.edu/media/catalog/product/5/9/598fa4dc3131dff06c11acffafcc0e6a.jpeg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:'},
      {'name': 'Guitar', 'image': 'https://www.soundunlimited.co.uk/cdn/shop/products/Valencia_3_4_VC203NA_91f76b46-5f4d-4139-adea-a56279e22d7c.jpg?v=1571306184&width=1080'},
      {'name': 'Gloves', 'image': 'https://karachifire.com/wp-content/uploads/2022/03/Nitrile-Gloves_1.jpg'},
      {'name': 'Glasses', 'image': 'https://www.tigerspecs.co.uk/products/1401028/detail.jpg'},
      {'name': 'Gator', 'image': 'https://blog.machinefinder.com/wp-content/uploads/2025/02/Screenshot-2025-02-25-at-12.34.44%E2%80%AFPM.png'},
      {'name': 'Goose', 'image': 'https://cdn4.volusion.store/kapts-nrbqf/v/vspfiles/photos/GOOSEEGG6-2T.jpg?v-cache=1590745950'},
      {'name': 'Garlic', 'image': 'https://www.veggycation.com.au/siteassets/veggycationvegetable/garlic.jpg'},
    ]),
    CharacterObjectModel(character: 'H', objects: [
      {'name': 'Horse', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'Hamster', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'Honeybee', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'House', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'Hat', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Hand', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Hare', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
      {'name': 'Hedgehog', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKF2MpLAHv1sM4hl5SuAASLrB7x4893b5fbg&s'},
      {'name': 'Helicopter', 'image': 'https://static.pakwheels.com/2016/09/corvette-engine.jpg'},
      {'name': 'Hammer', 'image': 'https://easydrawingguides.com/wp-content/uploads/2024/05/how-to-draw-an-emu-featured-image-1200.png'},
    ]),
    CharacterObjectModel(character: 'I', objects: [
      {'name': 'Ice Cream', 'image': 'https://thumbs.dreamstime.com/b/ice-cream-sundae-cone-white-background-clipping-path-ice-cream-sundae-cone-white-background-clipping-173644200.jpg'},
      {'name': 'Ice Cube', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMIWqZhIhof0LH7cXfkloI4dziwyZZnRj0GA&s'},
      {'name': 'Insect', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Insect_collage.png/1200px-Insect_collage.png'},
      {'name': 'Ibis', 'image': 'https://birda.twic.pics/species/0b71dfd4-8f6e-432b-87a6-c11bed47c8a3/reference_images/Australian_White_Ibis.jpg?twic=v1/contain=1200x628'},
      {'name': 'Ink Pen', 'image': 'https://www.indofuture.com/cdn/shop/files/1_9df48293-14ba-43d8-9100-eacebe200cdd.jpg?crop=center&height=794&v=1755657742&width=794'},
      {'name': 'Iron', 'image': 'https://pakref.com/wp-content/uploads/2021/12/national-iron-price-in-pakistan.jpg'},
      {'name': 'Island', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMKoiLAeT06UF-ATs4lg1ugSQ-qalCOnVGUg&s'},
      {'name': 'Igloo', 'image': 'https://media.istockphoto.com/id/497478950/photo/igloo.jpg?s=612x612&w=0&k=20&c=4Asa-KGIvR1PsXmGYH-l6ZGO2lXiG-v_QL8XipSIn8w='},
      {'name': 'Ice Cap', 'image': 'https://fiestamundoegypt.com/wp-content/uploads/2023/11/se-23.jpg'},
      {'name': 'Ice Bird', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlSQPIfYs2b-jXu2J1Ha6o5FZa16FiorHxh2r5w7fu2xKP0S1V6IcFtoHmeTGmUHj3VEY&usqp=CAU'},
    ]),
    CharacterObjectModel(character: 'J', objects: [
      {'name': 'Joker', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFbqNCGHO5-MsJzN4355F0PTKnK0nYUbgbqIOTaZVd_kNp3c1cmrFk8q5DcAGCrkNkOxY&usqp=CAU'},
      {'name': 'Jackfruit', 'image': 'https://malabardirect.com/cdn/shop/products/jackfruit.jpg?v=1601569905'},
      {'name': 'Joystick', 'image': 'https://row.hyperx.com/cdn/shop/files/hyperx_clutch_tanto_8b1s0aa_main_1.jpg?v=1711735921'},
      {'name': 'Jeans', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa2yBRD_kmhETDrrVlA-7c6MSUdaoqStN0jY9nG79-CtUyrKFBeCVpBuzcSFWCtkM9G_U&usqp=CAU'},
      {'name': 'Jewel', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI2tJ_KBw86xyey2Op56eMFO9wAzjR5iZjVQ&s'},
      {'name': 'Jeep', 'image': 'https://cache2.pakwheels.com/system/car_generation_pictures/3171/original/Jeep-Wrangler-3rd-gen.jpg?1449038587'},
      {'name': 'Jasmine', 'image': 'https://media.istockphoto.com/id/962855070/photo/jasmine-flowers-with-leaves-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=L5NOC6pQvEC9_OtoesWuv4VYTErN_oynAQ5-5OGaxpg='},
      {'name': 'Jacket', 'image': 'https://m.media-amazon.com/images/I/81OpqdKNqjL._AC_SL1500_.jpg'},
      {'name': 'Judge', 'image': 'https://www.shutterstock.com/image-vector/man-woman-wearing-judge-costume-600nw-2432239227.jpg'},
      {'name': 'Juice', 'image': 'https://www.lovefoodhatewaste.com/sites/default/files/styles/16_9_two_column/public/2022-08/Fruit-juice-sh1489857866.jpg.webp?itok=pdFMoZ6P'},
    ]),
    CharacterObjectModel(character: 'K', objects: [
      {'name': 'Kangaroo', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5w-eh_s-iQdRQA0aXQCAazktUSumS1-DAloBQUeV9FY89nzxYvmiW8V3bRqQ0msnwwe4&usqp=CAU'},
      {'name': 'Key', 'image': 'https://media.rs-online.com/F8773365-01.jpg'},
      {'name': 'King', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI-UV3n5L2G5UVd44Ph2xIM0be9klIU6oa5G9tFDigfPriigoSvdrYEUKBWoYXAcTS7H8&usqp=CAU'},
      {'name': 'Kid', 'image': 'https://media.istockphoto.com/id/467383049/photo/happy-little-boy-on-white-background.jpg?s=612x612&w=0&k=20&c=XhBp--Iel1-qSP3s7D8CrS3bLMXUIkijOR-m7RcsBTE='},
      {'name': 'Kiwi', 'image': 'https://www.mpg.de/11619430/original-1662552910.jpg?t=eyJ3aWR0aCI6OTY2LCJvYmpfaWQiOjExNjE5NDMwfQ%3D%3D--4af8ee582ec7bf65ba94b0a9ddb20ec30d7d7f27'},
      {'name': 'Knife', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR94QN58iEKf17gbcHu32WR8JhFZTFB-sIcwE80iOyTnXH8Vevk1HOaN9uZo3FBJFTe2bY&usqp=CAU'},
      {'name': 'Kernel', 'image': 'https://www.collinsdictionary.com/images/full/kernel_391651249.jpg'},
      {'name': 'Kingdom', 'image': 'https://thumbs.dreamstime.com/b/cartoon-castle-vector-fairytale-medieval-tower-fantasy-palace-building-kingdom-fairyland-illustration-childish-set-princess-131461255.jpg'},
      {'name': 'Kitchen', 'image': 'https://previews.123rf.com/images/elnradrf/elnradrf1411/elnradrf141100830/33660732-integral-kitchen-furniture-on-white-background.jpg'},
      {'name': 'Kite', 'image': 'https://cdn.vectorstock.com/i/1000v/25/64/colorful-kite-clipart-vector-57502564.jpg'},
    ]),
    CharacterObjectModel(character: 'L', objects: [
      {'name': 'Lion', 'image': 'https://media.istockphoto.com/id/628034316/vector/cartoon-lion-roaring.jpg?s=612x612&w=0&k=20&c=4Sv0JcyVxR46LW3SamTzM804qnj0vKdR4Ocv08LhCAM='},
      {'name': 'Leaf', 'image': 'https://media.istockphoto.com/id/177130309/photo/green-leaf.jpg?s=612x612&w=0&k=20&c=kYH00pTHwNEBkTZc_SrT1SDnN0SjXceblOIeq4rdASk='},
      {'name': 'Lamp', 'image': 'https://media.istockphoto.com/id/1398642201/photo/desk-lamp.jpg?s=612x612&w=0&k=20&c=1zMwXliVyBhhBbrwcMZqCoLrfyC8WabaIXZmiLaat5E='},
      {'name': 'Ladder', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMZn6civp5fLNShCEHekRQ6RweJG-f5nvAOQ&s'},
      {'name': 'Lemon', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToGX-93xUvDHUB__ARaRM23k-aalNZ5aweEsyAM2Vn8WNqs9HuOOypvdvuiLiMQEkLS5Y&usqp=CAU'},
      {'name': 'Lock', 'image': 'https://rukminim2.flixcart.com/image/480/640/xif0q/lock/u/c/x/push-brass-padlock-32-mm-stainless-steel-mini-auto-push-lock-original-imahem79fz2sgg2w.jpeg?q=90'},
      {'name': 'Lollipop', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/004/579/727/small/set-of-realistic-striped-colorful-lollipops-on-white-sticks-isolated-on-white-background-illustration-vector.jpg'},
      {'name': 'Laptop', 'image': 'https://image.made-in-china.com/2f0j00RTUCNPnlCucy/Honor-Magicbook-X14-PRO-Laptop-13th-Intel-Core-I5-13420h-Processor-FHD-14-Inch-Thin-and-Light-Laptop-Win11.webp'},
      {'name': 'Ladybug', 'image': 'https://ja-roy.com/wp-content/uploads/ladybug-1-1.webp'},
      {'name': 'Log', 'image': 'https://daily.wordreference.com/wp-content/uploads/2017/01/log.jpg'},
    ]),
    CharacterObjectModel(character: 'M', objects: [
      {'name': 'Mango', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCcqHhjcrdFPZuZiCBCg4K4aMc98gKE_OD4Q&s'},
      {'name': 'Monkey', 'image': 'https://classroomclipart.com/image/static7/preview2/photo-rhesus-monkey-isolated-on-white-background-62525.jpg'},
      {'name': 'Moon', 'image': 'https://t3.ftcdn.net/jpg/02/09/60/62/360_F_209606228_Koj9wMf6AC0a7vHboGeg1gdZvDMUDG5O.jpg'},
      {'name': 'Mouse', 'image': 'https://lh3.googleusercontent.com/proxy/CPNdhpAzvVMzBcNKDNHleAxgpuc1-EbwmYu6tSCBO_b0p7VKZiVI8JKwVSa-vj3FP_q614w8tk1OhCZQ2feV65ZoDlwPDoiAnINrmnrKYyswWu3HTOEt7boyoFXxiKw'},
      {'name': 'Mug', 'image': 'https://5.imimg.com/data5/EF/WM/MY-61149194/ceramic-coffee-mugs-11oz-plain-white-250x250.jpg'},
      {'name': 'Mushroom', 'image': 'https://media.istockphoto.com/id/2160058964/vector/set-with-edible-and-poisonous-mushrooms-chanterelles-porcini-mushrooms-fly-agarics-toadstools.jpg?s=612x612&w=0&k=20&c=tQj6gmll-3Yc2NH1pNTH4y5cEF5G6CXVaYQGLpXMIug='},
      {'name': 'Magnet', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXL0PDS-6Tiqrjgb1Hz7Aqhp_CBwOCogjXmn6qMees0uYg9CM04e0iyvhJ6l6mec6h22g&usqp=CAU'},
      {'name': 'Motorcycle', 'image': 'https://image.made-in-china.com/365f3j00aJEoPtqdAnbc/Haojue-Motorcycle-125-Haojue-Motorbike-YAMAHA-Motorcycle-Motorcycle-Parts.webp'},
      {'name': 'Mirror', 'image': 'https://c8.alamy.com/comp/P8EF35/mirror-cosmetic-clipping-path-isolated-on-white-background-P8EF35.jpg'},
      {'name': 'Map', 'image': 'https://cdn.vectorstock.com/i/1000v/05/90/world-map-in-four-colors-on-white-background-vector-23960590.jpg'},
    ]),
    CharacterObjectModel(character: 'N', objects: [
      {'name': 'Nest', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV7ilnh4Mxf2oVQG47YRRy-Hg4kgbKdiGR3LOyHa6v-N4NyoKKAPg45g2ETBbxVsjaLHY&usqp=CAU'},
      {'name': 'Nose', 'image': 'https://static.vecteezy.com/system/resources/previews/024/730/426/non_2x/human-nose-isolated-on-white-background-vector.jpg'},
      {'name': 'Net', 'image': 'https://media.istockphoto.com/id/1332853872/vector/fishing-net.jpg?s=612x612&w=0&k=20&c=89NMq3niQCRRjMs_h2tqES7pAGOwJpfn2U6JnVd8gpk='},
      {'name': 'Needle', 'image': 'https://chemyx.com/wp-content/uploads/2018/02/Screenshot-2024-05-29-131752.png'},
      {'name': 'Notebook', 'image': 'https://sugarpaper.com/cdn/shop/files/NBK75_LargeSpiralNotebook_Black_Cover.jpg?v=1702681330&width=1946'},
      {'name': 'Necklace', 'image': 'https://sc04.alicdn.com/kf/H6a8396371e16464e95c46cce7c28a81fQ.jpg'},
      {'name': 'Nail', 'image': 'https://st2.depositphotos.com/1835273/9204/i/950/depositphotos_92042316-stock-photo-nail-design-manicure-nails-crystals.jpg'},
      {'name': 'Newspaper', 'image': 'https://secondary.oslis.org/learn-to-research/plan/plan-possible-sources/images-for-plan-possible-sources/newspaper/@@images/image.jpeg'},
      {'name': 'Napkin', 'image': 'https://www.summerillandbishop.com/cdn/shop/files/PlainWhiteLinenNapkinNAPKINAb.jpg?v=1713977853'},
      {'name': 'Number', 'image': 'https://www.shopedx.co.uk/cdn/shop/products/75116_A_9f10d08f-5bba-443d-be6b-c3d9ff4091d2.jpg?v=1662383381'},
    ]),
    CharacterObjectModel(character: 'O', objects: [
      {'name': 'Orange', 'image': 'https://nippys.com.au/site/wp-content/uploads/2016/11/Orange_Shutterstock_600x600-600x600.jpeg'},
      {'name': 'Owl', 'image': 'https://www.shutterstock.com/image-vector/cartoon-cute-owl-clipart-ico-600nw-2603436473.jpg'},
      {'name': 'Octopus', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNxedy4XvlWosaekbY3HDr5-4HxUUlk57TQ&s'},
      {'name': 'Onion', 'image': 'https://5.imimg.com/data5/SELLER/Default/2025/7/532225377/TJ/OF/JU/204506206/20-kg-mesh-bag-large-red-onions-500x500.png'},
      {'name': 'Ox', 'image': 'https://cdn.britannica.com/18/63518-050-0A639C05/Shorthorn-bull.jpg'},
      {'name': 'Ocean', 'image': 'https://thumbs.dreamstime.com/b/blue-ocean-wave-splashing-water-isolated-white-background-ai-generated-394476168.jpg'},
      {'name': 'Oil bottle', 'image': 'https://static.vecteezy.com/system/resources/previews/020/809/294/large_2x/vegetable-oil-glass-bottle-isolated-on-white-background-with-clipping-path-organic-healthy-food-for-cooking-photo.jpg'},
      {'name': 'Ostrich', 'image': 'https://png.pngtree.com/thumb_back/fh260/background/20221112/pngtree-ostrich-isolated-isolated-feather-cut-photo-image_20473840.jpg'},
      {'name': 'Oven', 'image': 'https://e-lite.com.pk/cdn/shop/files/2_8_1.jpg?v=1756734348'},
      {'name': 'Oreo', 'image': 'https://springs.com.pk/cdn/shop/files/8961003026010.gif?v=1754920906'},
    ]),
    CharacterObjectModel(character: 'P', objects: [
      {'name': 'Parrot', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/022/684/543/small/cute-green-parrot-sitting-on-branch-cartoon-illustration-isolated-on-white-background-vector.jpg'},
      {'name': 'Penguin', 'image': 'https://img.pixers.pics/pho_wat(s3:700/FO/52/08/91/14/700_FO52089114_debb507d6bc3cc85cff1ac3d6a667022.jpg,550,700,cms:2018/10/5bd1b6b8d04b8_220x50-watermark.png,over,330,650,jpg)/stickers-cute-pinguin-cartoon-waving.jpg.jpg'},
      {'name': 'Pumpkin', 'image': 'https://www.healthxchange.sg/adobe/dynamicmedia/deliver/dm-aid--7f272a4e-bae5-42d0-ad04-d96dea3764ee/pumpkin-health-benefits-nutrition-facts.jpg?preferwebp=true'},
      {'name': 'Pineapple', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdGJ2stSwLyXiGWX5DHD2AS3wolBdsms0iqj35i65LJeT0Yrh6Rbjc_5NMLmMOkVgYFZc&usqp=CAU'},
      {'name': 'Pencil', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoKNn4tZsMVa-Hlooope0T95YqGOuiCJsMGA&s'},
      {'name': 'Pen', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/053/968/677/small/black-and-golden-pens-for-everyday-use-vector.jpg'},
      {'name': 'Panda', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT98lCsECxLnfOA2jJwAQGAr1NJ0NPMCT3ugsDN3YCSWK_Nh2DQdp0CvsvduPAe7s4OQ5c&usqp=CAU'},
      {'name': 'Peach', 'image': 'https://rukminim2.flixcart.com/image/300/300/xif0q/fruit/z/6/c/-original-imag3nyfzvqzgbmv.jpeg'},
      {'name': 'Pizza', 'image': 'https://www.shutterstock.com/image-photo/pepperoni-pizza-slice-on-transparent-600nw-2585448637.jpg'},
      {'name': 'Peacock', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6ZJSgmBhkRyXkw8E9ti3wUu_o1dULlbXTED7G9QIHhrfmwpGV0jXrOxQpQWiSOgqEnA&usqp=CAU'},
    ]),
    CharacterObjectModel(character: 'Q', objects: [
      {'name': 'Queen', 'image': 'https://thumbs.dreamstime.com/b/little-cute-queen-crown-cartoon-style-white-background-vector-illustration-271873851.jpg'},
      {'name': 'Quilt', 'image': 'https://www.myhomedecor.pk/wp-content/uploads/2021/09/Winter-Quilt-300x300.jpg'},
      {'name': 'Quail', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLsf_3_q4rlulP5ALxz-Jq8pmETCHBBbArnqzdBG1jN6He3QM8ZBCzQ16a6T91H-D0Ozw&usqp=CAU'},
      {'name': 'Quill', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3I_juWK-NkKrI3oysOfoW64eTOtqYGYVK0Q&s'},
      {'name': 'Quarter', 'image': 'https://t4.ftcdn.net/jpg/05/96/06/11/360_F_596061146_YLWhFwxPF57JneJxsUePzC8YVLnroYgh.jpg'},
      {'name': 'Quiver', 'image': 'https://img-va.myshopline.com/image/store/1722153248293/Arrow-Quiver-Brown-PU-Lenther-Archery-ameyxgs-archery-(6).jpeg?w=3000&h=3000'},
      {'name': 'Question mark', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1OGJ2c1tZonZdekK1upJPuwUvS-q56lRgxw&s'},
      {'name': 'Quokka', 'image': 'https://www.trudi.com/wp-content/uploads/2022/03/27144-B.jpg'},
      {'name': 'Quince', 'image': 'https://static.wikia.nocookie.net/fruit/images/c/c8/Quince.jpg/revision/latest?cb=20241205125210'},
      {'name': 'Quartz', 'image': 'https://media.istockphoto.com/id/1453829654/photo/quartz-cristals.jpg?s=612x612&w=0&k=20&c=988WgTvPdWuduFu-g8ixyKuO1WCNAcKf4gu-hAIt-l4='},
    ]),
    CharacterObjectModel(character: 'R', objects: [
      {'name': 'Rabbit', 'image': 'https://www.animaltrust.org.uk/_next/image?url=https://dashboard.animaltrust.org.uk/uploads/The_Best_Foods_For_A_Rabbit_2aba295465.png&w=3840&q=75'},
      {'name': 'Rainbow', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD91iXnonfzH9Ai7sLMWql8ngyXZRtlBsEfQ&s'},
      {'name': 'Rose', 'image': 'https://asset.bloomnation.com/c_fill,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,h_2000,q_auto,w_2000/v1747271921/vendor/8849/catalog/product/2/0/20230427064924_file_644ac3b47a996_644acbd21d4af.jpg'},
      {'name': 'Rocket', 'image': 'https://static.vecteezy.com/system/resources/previews/035/147/875/non_2x/ai-generated-space-rocket-on-transparent-background-image-png.png'},
      {'name': 'Ring', 'image': 'https://t3.ftcdn.net/jpg/05/64/35/80/360_F_564358021_KBRaemBSj9FGjZlupRQsloTJIMo1MATC.jpg'},
      {'name': 'Robot', 'image': 'https://www.ssla.co.uk/wp-content/uploads/2020/08/robot.jpg'},
      {'name': 'Ruler', 'image': 'https://stationers.pk/cdn/shop/products/rulerplastic.jpg?v=1673349616'},
      {'name': 'Rain', 'image': 'https://t3.ftcdn.net/jpg/09/09/96/66/360_F_909966605_3NfAWnuBA6dKqPDishvFA7LLFuSvnp4q.jpg'},
      {'name': 'Radio', 'image': 'https://addison-electronique.com/media/catalog/product/cache/9d1a036d0be553e2f53b6e43c28d0602/9/1/919337_ce58.jpg'},
      {'name': 'Road', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCGLqAm8qgloumu2726sda1KdFI4U19s0qfDV5kyA6ML7OUtb-tJ6eUUVu3CLdgOu8pFw&usqp=CAU'},
    ]),
    CharacterObjectModel(character: 'S', objects: [
      {'name': 'Sun', 'image': 'https://media.istockphoto.com/id/1124567572/vector/cute-flat-sun-icon.jpg?s=612x612&w=0&k=20&c=_ekkRvw-dX-3Dt-jH3tG8wonvYJ1NrBHEAEDFm4cGVc='},
      {'name': 'Star', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxCaIdksJQJbdgyuTwde0IjLKd7vLOJ9DzJg&s'},
      {'name': 'Snake', 'image': 'https://today.duke.edu/sites/default/files/2023-04/Northern_Water_Snake_Jeffrey_Beane.jpg'},
      {'name': 'Ship', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRujJLub9Bs7iCk_lZXxN7wG__v1pSiYDz98w&s'},
      {'name': 'Strawberry', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/012/483/672/small/whole-strawberry-fruit-and-sliced-segments-isolated-on-white-background-realistic-illustration-vector.jpg'},
      {'name': 'Spoon', 'image': 'https://t4.ftcdn.net/jpg/00/45/79/21/360_F_45792148_AoeR8fSO3oVirt95qEPIbBYDleFXaINb.jpg'},
      {'name': 'Socks', 'image': 'https://mpdenmark.com/cdn/shop/files/10_77194_0_302.jpg?v=1739434039&width=1080'},
      {'name': 'Snowman', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSejDPLf6zYCJeTL_j97AP9wFPfEdZAXeQfoQ&s'},
      {'name': 'Sandwich', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm9ClIyeHjXngB3i9DlEVqS3rSiQEMoEV4qw&s'},
      {'name': 'Scissors', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy7XZyId1Tc34KqaYSwGBEc0DeoeGPW5iT2g&s'},
    ]),
    CharacterObjectModel(character: 'T', objects: [
      {'name': 'Tiger', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf-7hwN3KtIJbbulvvfQBtCVTqEJOjKPxOLaaH5eaHJ_PnAPlM60A6GHS4FRJ_3WUmQYE&usqp=CAU'},
      {'name': 'Table', 'image': 'https://www.simpli-home.com/cdn/shop/files/AXCDNT-003-OAK_Silo_Detail_1.jpg?v=1750784610&width=2560'},
      {'name': 'Tree', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxV06K6Ex7qMdbOXX6As7YKjNiISoWEh2BmQ&s'},
      {'name': 'Train', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe6zZTVHgxcndlO-b9dHbQLmrxcr7zS7jn9A&s'},
      {'name': 'Tomato', 'image': 'https://source.washu.edu/app/uploads/2015/11/Tomato250.jpg'},
      {'name': 'Turtle', 'image': 'https://t3.ftcdn.net/jpg/02/12/04/16/360_F_212041631_IlUpamHEbdvRMmzfuXav1XORBnaIXuEf.jpg'},
      {'name': 'Truck', 'image': 'https://res.cloudinary.com/dy7f2kupd/image/upload/co_white/c_fill,q_auto:best/v1/uploads/udtrucks/2303002.jpg'},
      {'name': 'Telephone', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvmC27LojFm9j2TXkJQwtu9VUnp-wkCyp6gw&s'},
      {'name': 'Toothbrush', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/054/082/314/small/lovely-cartoon-manual-toothbrush-for-teeth-treatment-and-cavity-hygiene-cute-hand-drawn-brush-for-dental-care-and-protection-from-caries-stomatology-and-healthcare-clipart-isolated-on-background-vector.jpg'},
      {'name': 'Towel', 'image': 'https://flyingcart.pk/cdn/shop/files/1_0c4140fc-6bce-407b-b077-a24e5bebbce2.jpg?v=1729674393'},
    ]),
    CharacterObjectModel(character: 'U', objects: [
      {'name': 'Umbrella', 'image': 'https://static-01.daraz.pk/p/63edcd1f2085c0402891b13de56affbc.jpg'},
      {'name': 'Unicorn', 'image': 'https://www.shutterstock.com/image-vector/cute-cartoon-rainbow-unicorn-vector-600nw-2487769365.jpg'},
      {'name': 'Uniform', 'image': 'https://m.media-amazon.com/images/I/61R12SK3BUL._AC_SL1100_.jpg'},
      {'name': 'Urn', 'image': 'https://loveurns.com/cdn/shop/files/A231_5a1b1f73-b448-4f49-90fe-1dbb13cbbd40_5000x.jpg?v=1725028408'},
      {'name': 'Utensils', 'image': 'https://static.vecteezy.com/system/resources/thumbnails/025/464/377/small/big-set-of-kitchen-utensils-silhouette-spatulas-hand-mixer-spoons-ladles-tongs-icons-vector.jpg'},
      {'name': 'USB', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROSajGQLRejFpHuNirkByxiPaV5CRvgmxK-Q&s'},
      {'name': 'Universe', 'image': 'https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA4L3B4ODM3MDQxLWltYWdlLWpvYjg1MS5qcGc.jpg'},
      {'name': 'Urchin', 'image': 'https://media.istockphoto.com/id/1045231500/vector/urchin-cartoon.jpg?s=612x612&w=0&k=20&c=jXSXzSZyZkwi0daQ0Y1-H1NGbXWkK65ktlPYLDp6g-E='},
      {'name': 'Ukulele', 'image': 'https://r2.gear4music.com/media/68/681080/600/preview_1.jpg'},
      {'name': 'UFO', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxBwNL-ohBohG5j7vz-LYBVkXpJfknkYomgQ&s'},
    ]),
    CharacterObjectModel(character: 'V', objects: [
      {'name': 'Van', 'image': 'https://media.istockphoto.com/id/2149237608/photo/van-with-empty-side-space-for-design-transport-car-mock-up-delivery-van-isolated-on-white.jpg?s=612x612&w=0&k=20&c=mPSRjRGuABnHIUBUUOP3JYQy2t6ebEtO9HYNuBPBp34='},
      {'name': 'Violin', 'image': 'https://media.istockphoto.com/id/883076126/vector/violin.jpg?s=612x612&w=0&k=20&c=8z6nviNbwp6er1da6jR19SNpV-o760Q5IC1FDRN9q28='},
      {'name': 'Vase', 'image': 'https://us.123rf.com/450wm/goodstudio/goodstudio2410/goodstudio241000305/237359903-flower-bouquet-in-vase-summer-floral-arrangement-simple-blooming-wildflowers-gentle-field-and.jpg?ver=6'},
      {'name': 'Volcano', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI2PHAC52ttegOzGQEIOYlywcoueroDKYtWQ&s'},
      {'name': 'Vegetables', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-pM2cVm5aP1LOpQmwK2y41Ohv81XUmeds5g&s'},
      {'name': 'Vest', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD6jAZUrGbCWte0KJx3u_Clh4XpNhB-1qA3_LiCiklV42tEvyuCw9w3i6ckjgdJuOorz4&usqp=CAU'},
      {'name': 'Vacuum Cleaner', 'image': 'https://i5.walmartimages.com/seo/Eureka-Whirlwind-Canister-Vacuum-NEN110F-New_3956abde-4a9e-4937-8b88-3948ce14ce9d.ff364eac54a371b44bbe0a0e5b5efe60.jpeg'},
      {'name': 'Vulture', 'image': 'https://bioexpedition.com/wp-content/uploads/2012/04/King_Vulture_Sarcoramphus_Papa_600.jpg'},
      {'name': 'Vampire', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCW5LYg9b6EOQ-_FCEm2v-uPUHPl92IUsq0g&s'},
      {'name': 'Video Camera', 'image': 'https://media.istockphoto.com/id/91265348/photo/professional-digital-video-camera-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=eGL67oBmKIejMNZfCaJaME5bJMtIu0Z4NFSf3R7h29g='},
    ]),
    CharacterObjectModel(character: 'W', objects: [
      {'name': 'Watch', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'Window', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'Whale', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'Wolf', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'Worm', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Wheel', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Wings', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
      {'name': 'Wall', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKF2MpLAHv1sM4hl5SuAASLrB7x4893b5fbg&s'},
      {'name': 'Wagon', 'image': 'https://static.pakwheels.com/2016/09/corvette-engine.jpg'},
      {'name': 'Watermelon', 'image': 'https://easydrawingguides.com/wp-content/uploads/2024/05/how-to-draw-an-emu-featured-image-1200.png'},
    ]),
    CharacterObjectModel(character: 'X', objects: [
      {'name': 'Xylophone', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'X-ray', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'X-ray Fish', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'X-mas Tree', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'X-axis', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Xylograph', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Xerox Machine', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
    ]),
    CharacterObjectModel(character: 'Y', objects: [
      {'name': 'Yak', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'Yarn', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'Yam', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'Yacht', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'Yo-yo', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Yellow', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Yogurt', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
      {'name': 'Yard', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKF2MpLAHv1sM4hl5SuAASLrB7x4893b5fbg&s'},
    ]),
    CharacterObjectModel(character: 'Z', objects: [
      {'name': 'Zebra', 'image': 'https://t3.ftcdn.net/jpg/05/49/49/82/360_F_549498276_AFnuz8nRNKBwHEiPDt86NacMrnEn13ib.jpg'},
      {'name': 'Zip', 'image': 'https://ca.schleich-s.com/cdn/shop/products/14763_main_v16_TP.jpg?v=1691537299'},
      {'name': 'Zipper', 'image': 'https://img.pikbest.com/origin/09/69/99/76xpIkbEsTJzI.png!sw800'},
      {'name': 'Zoo', 'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Earwig_on_white_background.jpg/1200px-Earwig_on_white_background.jpg'},
      {'name': 'Zero', 'image': 'https://5.imimg.com/data5/BF/UU/NJ/SELLER-83011653/plain-paper-envelope-design-500x500.jpg'},
      {'name': 'Zigzag', 'image': 'https://i.pinimg.com/474x/49/4c/92/494c92c5e909cac6fb80ffc9be0fb8a9.jpg'},
      {'name': 'Zombie', 'image': 'https://media.istockphoto.com/id/1394801910/vector/realistic-human-ear-isolated-on-white-background-human-ear-organ-hearing-health-care-closeup.jpg?s=612x612&w=0&k=20&c=Sz7uFiG7-aXja7r7M8qaSuH_7AicbixpuKB87LWKXbA='},
      {'name': 'Zucchini', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKF2MpLAHv1sM4hl5SuAASLrB7x4893b5fbg&s'},
    ]),
  ].obs;

  RxInt currentIndex = 0.obs;
  RxString stage = 'study'.obs;

  void nextCharacter() {
    if (currentIndex.value < charactersList.length - 1) {
      currentIndex.value++;
      stage.value = 'study';
    }
  }

  void changeStage(String newStage) {
    stage.value = newStage;
  }
  Future<void> speakObject(String character, String objectName) async {
    await flutterTts.speak("$character for $objectName");
  }

  @override
  void onClose() {
    flutterTts.stop();
    super.onClose();
  }
}
